# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/struktured/release/2.0.0/src/libprojectM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/struktured/release/2.0.0/src/libprojectM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/struktured/release/2.0.0/src/libprojectM/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/struktured/release/2.0.0/src/libprojectM/CMakeFiles /home/struktured/release/2.0.0/src/libprojectM/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/struktured/release/2.0.0/src/libprojectM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named projectM

# Build rule for target.
projectM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 projectM
.PHONY : projectM

# fast build rule for target.
projectM/fast:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/build
.PHONY : projectM/fast

#=============================================================================
# Target rules for targets named NativePresetFactory

# Build rule for target.
NativePresetFactory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NativePresetFactory
.PHONY : NativePresetFactory

# fast build rule for target.
NativePresetFactory/fast:
	$(MAKE) -f NativePresetFactory/CMakeFiles/NativePresetFactory.dir/build.make NativePresetFactory/CMakeFiles/NativePresetFactory.dir/build
.PHONY : NativePresetFactory/fast

#=============================================================================
# Target rules for targets named MilkdropPresetFactory

# Build rule for target.
MilkdropPresetFactory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MilkdropPresetFactory
.PHONY : MilkdropPresetFactory

# fast build rule for target.
MilkdropPresetFactory/fast:
	$(MAKE) -f MilkdropPresetFactory/CMakeFiles/MilkdropPresetFactory.dir/build.make MilkdropPresetFactory/CMakeFiles/MilkdropPresetFactory.dir/build
.PHONY : MilkdropPresetFactory/fast

#=============================================================================
# Target rules for targets named Renderer

# Build rule for target.
Renderer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Renderer
.PHONY : Renderer

# fast build rule for target.
Renderer/fast:
	$(MAKE) -f Renderer/CMakeFiles/Renderer.dir/build.make Renderer/CMakeFiles/Renderer.dir/build
.PHONY : Renderer/fast

# target to build an object file
ConfigFile.o:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/ConfigFile.o
.PHONY : ConfigFile.o

# target to preprocess a source file
ConfigFile.i:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/ConfigFile.i
.PHONY : ConfigFile.i

# target to generate assembly for a file
ConfigFile.s:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/ConfigFile.s
.PHONY : ConfigFile.s

# target to build an object file
KeyHandler.o:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/KeyHandler.o
.PHONY : KeyHandler.o

# target to preprocess a source file
KeyHandler.i:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/KeyHandler.i
.PHONY : KeyHandler.i

# target to generate assembly for a file
KeyHandler.s:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/KeyHandler.s
.PHONY : KeyHandler.s

# target to build an object file
PCM.o:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PCM.o
.PHONY : PCM.o

# target to preprocess a source file
PCM.i:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PCM.i
.PHONY : PCM.i

# target to generate assembly for a file
PCM.s:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PCM.s
.PHONY : PCM.s

# target to build an object file
PipelineMerger.o:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PipelineMerger.o
.PHONY : PipelineMerger.o

# target to preprocess a source file
PipelineMerger.i:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PipelineMerger.i
.PHONY : PipelineMerger.i

# target to generate assembly for a file
PipelineMerger.s:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PipelineMerger.s
.PHONY : PipelineMerger.s

# target to build an object file
Preset.o:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/Preset.o
.PHONY : Preset.o

# target to preprocess a source file
Preset.i:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/Preset.i
.PHONY : Preset.i

# target to generate assembly for a file
Preset.s:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/Preset.s
.PHONY : Preset.s

# target to build an object file
PresetChooser.o:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PresetChooser.o
.PHONY : PresetChooser.o

# target to preprocess a source file
PresetChooser.i:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PresetChooser.i
.PHONY : PresetChooser.i

# target to generate assembly for a file
PresetChooser.s:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PresetChooser.s
.PHONY : PresetChooser.s

# target to build an object file
PresetFactory.o:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PresetFactory.o
.PHONY : PresetFactory.o

# target to preprocess a source file
PresetFactory.i:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PresetFactory.i
.PHONY : PresetFactory.i

# target to generate assembly for a file
PresetFactory.s:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PresetFactory.s
.PHONY : PresetFactory.s

# target to build an object file
PresetFactoryManager.o:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PresetFactoryManager.o
.PHONY : PresetFactoryManager.o

# target to preprocess a source file
PresetFactoryManager.i:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PresetFactoryManager.i
.PHONY : PresetFactoryManager.i

# target to generate assembly for a file
PresetFactoryManager.s:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PresetFactoryManager.s
.PHONY : PresetFactoryManager.s

# target to build an object file
PresetLoader.o:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PresetLoader.o
.PHONY : PresetLoader.o

# target to preprocess a source file
PresetLoader.i:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PresetLoader.i
.PHONY : PresetLoader.i

# target to generate assembly for a file
PresetLoader.s:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/PresetLoader.s
.PHONY : PresetLoader.s

# target to build an object file
TimeKeeper.o:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/TimeKeeper.o
.PHONY : TimeKeeper.o

# target to preprocess a source file
TimeKeeper.i:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/TimeKeeper.i
.PHONY : TimeKeeper.i

# target to generate assembly for a file
TimeKeeper.s:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/TimeKeeper.s
.PHONY : TimeKeeper.s

# target to build an object file
fftsg.o:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/fftsg.o
.PHONY : fftsg.o

# target to preprocess a source file
fftsg.i:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/fftsg.i
.PHONY : fftsg.i

# target to generate assembly for a file
fftsg.s:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/fftsg.s
.PHONY : fftsg.s

# target to build an object file
projectM.o:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/projectM.o
.PHONY : projectM.o

# target to preprocess a source file
projectM.i:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/projectM.i
.PHONY : projectM.i

# target to generate assembly for a file
projectM.s:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/projectM.s
.PHONY : projectM.s

# target to build an object file
timer.o:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/timer.o
.PHONY : timer.o

# target to preprocess a source file
timer.i:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/timer.i
.PHONY : timer.i

# target to generate assembly for a file
timer.s:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/timer.s
.PHONY : timer.s

# target to build an object file
wipemalloc.o:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/wipemalloc.o
.PHONY : wipemalloc.o

# target to preprocess a source file
wipemalloc.i:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/wipemalloc.i
.PHONY : wipemalloc.i

# target to generate assembly for a file
wipemalloc.s:
	$(MAKE) -f CMakeFiles/projectM.dir/build.make CMakeFiles/projectM.dir/wipemalloc.s
.PHONY : wipemalloc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... projectM"
	@echo "... rebuild_cache"
	@echo "... NativePresetFactory"
	@echo "... MilkdropPresetFactory"
	@echo "... Renderer"
	@echo "... ConfigFile.o"
	@echo "... ConfigFile.i"
	@echo "... ConfigFile.s"
	@echo "... KeyHandler.o"
	@echo "... KeyHandler.i"
	@echo "... KeyHandler.s"
	@echo "... PCM.o"
	@echo "... PCM.i"
	@echo "... PCM.s"
	@echo "... PipelineMerger.o"
	@echo "... PipelineMerger.i"
	@echo "... PipelineMerger.s"
	@echo "... Preset.o"
	@echo "... Preset.i"
	@echo "... Preset.s"
	@echo "... PresetChooser.o"
	@echo "... PresetChooser.i"
	@echo "... PresetChooser.s"
	@echo "... PresetFactory.o"
	@echo "... PresetFactory.i"
	@echo "... PresetFactory.s"
	@echo "... PresetFactoryManager.o"
	@echo "... PresetFactoryManager.i"
	@echo "... PresetFactoryManager.s"
	@echo "... PresetLoader.o"
	@echo "... PresetLoader.i"
	@echo "... PresetLoader.s"
	@echo "... TimeKeeper.o"
	@echo "... TimeKeeper.i"
	@echo "... TimeKeeper.s"
	@echo "... fftsg.o"
	@echo "... fftsg.i"
	@echo "... fftsg.s"
	@echo "... projectM.o"
	@echo "... projectM.i"
	@echo "... projectM.s"
	@echo "... timer.o"
	@echo "... timer.i"
	@echo "... timer.s"
	@echo "... wipemalloc.o"
	@echo "... wipemalloc.i"
	@echo "... wipemalloc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

